#!/usr/bin/env bash

VERSION="0.1.0"
COPY=false
FZF=false

if [ -t 1 ]; then
	VERBOSE=1
else
	VERBOSE=
fi

log() {
	echo -e "$(tput setaf 2)✔︎ $*$(tput sgr0)"
}

die() {
	echo -e "$(tput setaf 1)✘ $*$(tput sgr0)" >&2
	exit 1
}

usage() {
	cat <<-EOF

		Usage:
		$0 [options] [networks]

		Options:
		-c | --copy     Copy the password to pbcopy
		-f | --fzf      Choose network with fzf (note: cannot pass networks)
		-V | --version  Print version
		-h | --help     Print this message
		        -q | --quiet    Suppress output

	EOF
	exit 0
}

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
	case $1 in
	-c | --copy)
		COPY=true
		;;
	-f | --fzf)
		FZF=true
		;;
	-V | --version)
		echo "version $VERSION"
		exit 0
		;;
	-q | --quiet)
		VERBOSE=
		;;
	-h | --help)
		usage
		;;
	esac
	shift
done

if $FZF && [[ $# -ne 0 ]]; then
	die "Cannot pass network arguments when using the -f (fzf) option."
fi

if $FZF && ! command -v fzf &>/dev/null; then
	die "fzf is not installed. Please install it to use the -f option."
fi

if [[ $# -eq 0 ]]; then
	if $FZF; then
		NETWORK=$(networksetup -listpreferredwirelessnetworks en0 2>/dev/null | sed '1d' | tr -d '\t' | fzf --preview='')
		if [[ -z "$NETWORK" ]]; then
			die "No network selected or found."
		fi
	else
		NETWORK=$(networksetup -listpreferredwirelessnetworks en0 2>/dev/null | sed -n '2 p' | tr -d '\t')
		if [[ -z "$NETWORK" ]]; then
			die "No default network found. Please specify a network or use -f."
		fi
	fi
else
	NETWORK=$*
fi

if [ $VERBOSE ]; then
	log "Using network $NETWORK"
	log "Keychain prompt incoming..."
fi

if $COPY; then
	if ! security find-generic-password -wa "$NETWORK" 2>/dev/null | pbcopy; then
		die "Failed to copy password for '$NETWORK'. It might not be in your keychain."
	fi
else
	if ! security find-generic-password -wa "$NETWORK" 2>/dev/null; then
		die "Failed to find password for '$NETWORK'. It might not be in your keychain."
	fi
fi
